### ISSUE TITLE
[FEAT] 로그인/회원가입 페이지 구현

### ISSUE THREAD

**Issue by hurryduck** [jonghoko1/BitData#55]
#To-Do
- [x] 백도어 페이지 삭제
- [x] 로그인 회원가입 버튼 활성화
- [x] 회원가입 페이지 활성화
- [x] 개인정보 수집동의 업데이트 하기
- [x] 배포
